languageCode = "en-gb"
baseurl = "https://pjgill.net/"
title = "PGill"
copyright = "Phoebe Gill"
theme = "ghostwriter"
canonifyurls = true

[Author]
    name = "Phoebe Gill"

[Params]
    intro = true
    headline = "Idle chatter of a transcendental kind"
    github = "https://github.com/phoebe-gill"
    email = "website@pjgill.net"
    opengraph = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[[menu.main]]
    name = "Links"
    url = "/page/links/"
    weight = 5
